//react
import { useEffect, useState } from 'react';
//style
import './Project.css';
//importing images
import easynpsLogo from '../../images/logos/easynpsLogo.jpg'
//fontawesome
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faHeart, faSearch, faCode, faChevronLeft, faChevronRight, faCircle, faCaretLeft, faLightbulb, faUserTie, faCogs, faCheckCircle, faImages, faPuzzlePiece } from '@fortawesome/free-solid-svg-icons';
//screenshots
import screenshot from '../../images/screenshots/phone_preview.jpg'
import screenshot1 from '../../images/screenshots/phone_preview1.jpg'
import screenshot2 from '../../images/screenshots/phone_preview2.jpg'
import screenshot3 from '../../images/screenshots/phone_preview3.jpg'
//technologies used
import reactLogo from '../../images/logos/react.png'
import nodeLogo from '../../images/logos/nodejs.png'
import mongoLogo from '../../images/logos/mongodb.png'

function Project(){
    const [slideImages] = useState([
        {id:0,src:screenshot},
        {id:1,src:screenshot2},
        {id:2,src:screenshot3},
        {id:3,src:screenshot1}
    ]);

    const [slide, setSlide] = useState(0);

    function slideLeft(){
        if(slide===0){
            setSlide(slideImages.length-1)
        }else{
            setSlide(slide-1)
        }  
    }
    function slideRight(){
        if(slide === slideImages.length-1){
            setSlide(0)
        }else{
            setSlide(slide+1)
        }  
    }

    useEffect(()=>{
        const rs = document.querySelector(':root').style;
          rs.setProperty('--slide',slide);
        }, [slide]);

    return(
        <>
        <div className='navigation-container'>
            <a href="/#exp" className='home-button'>
                <FontAwesomeIcon icon={faCaretLeft} />
            </a>
        </div>
        <div className='project-head-container'>
            <div className='project-image-container'>
                <img className='project-image' src={easynpsLogo} alt=""/>
                <button className='project-button like-button'><FontAwesomeIcon icon={faHeart} className='like-icon'/> 2 Likes</button>
            </div>
            <div className='project-info'>
                <h1 className='project-title'>Easy NPS</h1>
                <h6 className='project-description'>Easy NPS is a tool that makes the completion of customer satisfaction surveys in retail stores easy. Customers can now simply access surveys by scanning a QR code generated by a sales associate.</h6>
            </div>
            <div className='project-button-container'>
                <div className='project-button-container'>
                    <a href="https://www.easynps.ca/" target="_blank" rel='noreferrer'><button className='project-button'><FontAwesomeIcon icon={faSearch} className='like-icon'/> Live Preview</button></a>
                    <a href="https://github.com/omarboulbaze/easynps" target="_blank" rel='noreferrer'><button className='project-button'><FontAwesomeIcon icon={faCode} className='like-icon'/> Source Code</button></a>
                </div>
            </div>
        </div>
        <div className='project-body-container'>
            <div  className='project-section-title'>
                 <h2><FontAwesomeIcon icon={faImages} style={{fontSize:"2rem", marginRight:"1rem", opacity:"0.6"}}/>Preview</h2>
            </div>
            <div className='project-slide'>
                <button className='project-slide-button-left hover-opacity-1' onClick={()=>slideLeft()}><FontAwesomeIcon icon={faChevronLeft}/></button>
                {
                    slideImages.map(img => {
                        return <img key={img.id} className='project-slide-image' src={img.src} alt=""/>
                    })
                }
                <button className='project-slide-button-right hover-opacity-1' onClick={()=>slideRight()}><FontAwesomeIcon icon={faChevronRight}/></button>
            </div>
            <div className='slide-points'>
                {
                    slideImages.map((img)=>{
                        if(slide===img.id){
                            return <button key={img.id} className='slide-points-button hover-opacity-1 active-slide-button' onClick={()=> setSlide(img.id)}><FontAwesomeIcon icon={faCircle}/></button>
                        }else{
                            return <button key={img.id} className='slide-points-button hover-opacity-1' onClick={()=> setSlide(img.id)}><FontAwesomeIcon icon={faCircle}/></button>
                        }
                        
                    })
                }
            </div>
        </div>
        <div className='general-container'>
        <div className='tech-container'>
        <div  className='project-section-title'>
                 <h2><FontAwesomeIcon icon={faCogs} style={{fontSize:"2rem", marginRight:"1rem", opacity:"0.6"}}/>Technologies Used</h2>
                    <div className='tech-used-container'>
                        <div className='tech-used-item'>
                            <img src={reactLogo} alt=''/>
                            <span>React.js</span>
                        </div>
                        <div className='tech-used-item'>
                            <img src={nodeLogo} alt=''/>
                            <span>Node.js</span>
                        </div>
                        <div className='tech-used-item'>
                            <img src={mongoLogo} alt=''/>
                            <span>MongoDB</span>
                        </div>
                    </div>
                    
            </div>
        </div>
        <div className='role-container'>
        <div  className='project-section-title'>
                 <h2><FontAwesomeIcon icon={faUserTie} style={{fontSize:"2rem", marginRight:"1rem", opacity:"0.6"}}/>My Role</h2>
                    <p>
                        My main goal is to make a Full-Stack Web Application. Implementing a responsive UI design combined with optimized UX concepts. The data is stored in a MongoDB as a database 
                        while using NodeJS as the runtime environment.
                    </p>  
            </div>
        </div>
        </div>
        <div className='features-container'>
        <div  className='feature-section'>
                 <h2 style={{fontWeight:"bold"}}><FontAwesomeIcon icon={faLightbulb} style={{fontSize:"2rem", marginRight:"1rem", color:"#ffcb3d", opacity:"0.6"}}/>Notable Features</h2>
                        <ul>
                            <li>QR Code generator making the access to the survey easier.</li>
                            <li>Responsive design on web and mobile using CSS3.</li>
                            <li>Code Athentification in order to avoid duplicate reviews.</li>
                            <li>"Remember me" feature (Associate's informations) when generating a QR code, making it faster for the sales associates.</li>
                        </ul> 
        </div>
        </div>
        <div className='difficulty-solution-container'>
        <div className='role-container'>
            <div  className='project-section-title'>
                    <h2><FontAwesomeIcon icon={faPuzzlePiece} style={{fontSize:"2rem", marginRight:"1rem", color:"#ff2b2b", opacity:"0.6"}}/>Project Challenges</h2>
                        <ul>
                            <li>Fast and responsive layout on mobile. 100% of our users are on mobile since the QR Code is scanned using their camera.</li>
                            <li>Minimalist UI/UX for Sales Associates. The QR code generator tool should be simple and efficient.</li>
                        </ul>
            </div>
        </div>
        <div className='role-container'>
        <div  className='project-section-title'>
                 <h2><FontAwesomeIcon icon={faCheckCircle} style={{fontSize:"2rem", marginRight:"1rem", color:"#60de49", opacity:"0.6"}}/>My Solutions</h2>
                    <ul>
                        <li>Deploying the application as a PWA (Progressive Web Application), giving users multiples advantages similar to a native application.</li>
                        <li>Giving employees the possibility of saving Easy NPS on their homescreen and generating QR codes while offline.</li>

                    </ul>  
            </div>
        </div>
        </div>
        
        
        </>
    )
}

export default Project; 